describe('Test login', () => {
	it('Should get errors after wrong username is submitted', () => {
		cy.visit('/')
		cy.get('.userField')
		  .type('wrongusername')
		  .should('have.value', 'wrongusername')
		cy.get('.loginBtn')
		  .click()
		cy.contains('Username not found')
	})
	it('Should be able to login after writing username and submitting', () => {
		cy.visit('/')
		cy.get('.userField')
		  .type('sudo')
		  .should('have.value', 'sudo')
		cy.get('.loginBtn')
		  .click()
		cy.url().should('include', '/films')
		cy.get('.App-container')
		  .find('img')
		  .should('have.length', 250)
		cy.get('.App-container')
		  .find('img')
		  .first()
		  .click()
		cy.url().should('include', '/films/tt0111161')
	})
})
